### PR TITLE
task1: bluehawana

### PR DESCRIPTION
**Pull request by bluehawana**
## PR规范

注册的 PR，命名为 `init: user-name`，例如 `init: Beavnvvv`

提交 task 的 PR，命名为 `task[n]: user-name`，例如： `task0: Beavnvvv`

需要编写网页的 `task`，请在描述中上传效果截图。

**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**  
**请不要把报名和提交TASK的内容合并到一起，也不要将多个TASK放到一起提交！**

### CODE REVIEW

**Comment by bluehawana** [comment]
Would you please view my PR so I could do a new pr for my task 0 which is registration, thanks a lot.

**Comment by bluehawana** [comment]
Thanks for your reply, No worries about your English, I got what you mean and have changed my structures on both github and on preem and done with three new PR. Please review them if possible, thanks for your time and help.

**Comment by ourai** [comment]
But all of them are the same as this PR...

**Comment by bluehawana** [comment]
Hi again，I found the role of our project's PR until I finished Task2. So do you mean that I need to deleted all my finished tasks and begin from the init step？ Or I can change some contents to make it three PR theoretically?

**Pull request merged**
