### PR TITLE
task3: lispking

### PR DESCRIPTION
**Pull request by lispking**
- Contract MyToken deployed successfully: [0xe69dcae5a6ca1dce3bebfd5264a83436951c6f43](https://sepolia.etherscan.io/address/0xe69dcae5a6ca1dce3bebfd5264a83436951c6f43)

- Contract MyNFT deployed successfully: [0xdD65F5D3a5AEE68769267a5663CCcD213b45ABaA](https://sepolia.etherscan.io/address/0xdD65F5D3a5AEE68769267a5663CCcD213b45ABaA)

- Contract NFTMarket deployed successfully: [0xee9e3a49eca927933ef08c742ce2e0a89bedd419](https://sepolia.etherscan.io/address/0xee9e3a49eca927933ef08c742ce2e0a89bedd419)

- 用户A上架NFT的hash: [0xe16f21787f928ce96e915fc6bd54b9f03344ea1aee9432472d7561a822faef06](https://sepolia.etherscan.io/tx/0xe16f21787f928ce96e915fc6bd54b9f03344ea1aee9432472d7561a822faef06)

- 用户B购买NFT的交易哈希: [0x7df59c9cf3e32fb528f5b25d33fb2f22adf81b94c560147b27458b1e0c9bd1b1](https://sepolia.etherscan.io/tx/0x7df59c9cf3e32fb528f5b25d33fb2f22adf81b94c560147b27458b1e0c9bd1b1)

### CODE REVIEW

**Review by linghuccc — CHANGES_REQUESTED** [review]
task3 只需要 solidity 文件+哈希

**Comment by lispking** [comment]
这种就没必要限制太死了，这是线上业务的做法，应该让大家学习如何做规范项目，而不仅仅是写合约

**Comment by lispking** [comment]
已经非常无语的更新，只保留合约了

**Review by linghuccc — CHANGES_REQUESTED** [review]
请提供上架 NFT 的哈希，谢谢

**Comment by lispking** [comment]
https://sepolia.etherscan.io/address/0x2eAE552E27435D5f395248ba3002930B5D29d5E9

这合约地址下面的List Item全是上架 hash

https://sepolia.etherscan.io/tx/0xe16f21787f928ce96e915fc6bd54b9f03344ea1aee9432472d7561a822faef06
https://sepolia.etherscan.io/tx/0x3c700cb82582bcef8e05feb47a13ba16ff58379dee7470ce8f8534a16b39098e

**Review by linghuccc — CHANGES_REQUESTED** [review]
买家和卖家请使用不同的地址，谢谢

**Comment by lispking** [comment]
https://sepolia.etherscan.io/tx/0x7df59c9cf3e32fb528f5b25d33fb2f22adf81b94c560147b27458b1e0c9bd1b1
不同的购买NFT地址

**Comment by lispking** [comment]
https://sepolia.etherscan.io/address/0xee9e3a49eca927933ef08c742ce2e0a89bedd419
合约都改了N版本了，都3周前的事情，具体看这里新版合约的上架和购买交易

**Comment by lispking** [comment]
- Contract MyToken deployed successfully: [0xe69dcae5a6ca1dce3bebfd5264a83436951c6f43](https://sepolia.etherscan.io/address/0xe69dcae5a6ca1dce3bebfd5264a83436951c6f43)

- Contract MyNFT deployed successfully: [0xdD65F5D3a5AEE68769267a5663CCcD213b45ABaA](https://sepolia.etherscan.io/address/0xdD65F5D3a5AEE68769267a5663CCcD213b45ABaA)

- Contract NFTMarket deployed successfully: [0xee9e3a49eca927933ef08c742ce2e0a89bedd419](https://sepolia.etherscan.io/address/0xee9e3a49eca927933ef08c742ce2e0a89bedd419)

- 用户A上架NFT的hash: [0xe16f21787f928ce96e915fc6bd54b9f03344ea1aee9432472d7561a822faef06](https://sepolia.etherscan.io/tx/0xe16f21787f928ce96e915fc6bd54b9f03344ea1aee9432472d7561a822faef06)

- 用户B购买NFT的交易哈希: [0x7df59c9cf3e32fb528f5b25d33fb2f22adf81b94c560147b27458b1e0c9bd1b1](https://sepolia.etherscan.io/tx/0x7df59c9cf3e32fb528f5b25d33fb2f22adf81b94c560147b27458b1e0c9bd1b1)

**Comment by lispking** [comment]
已更新

**Pull request merged**
